server:
  port: 9086

spring:
  datasource:
    url: jdbc:mysql://39.108.174.27:3306/activiti?characterEncoding=utf-8
    username: phoenix
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  activiti:
    db-history-used: true