spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.bruse.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
    address: spring-cloud://localhost

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/