server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.188/ordermanager?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT
    username: oms
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bruse.mybatis.entity
