server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.188/ordermanager?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT
    username: oms
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 39.108.174.27
    port: 6379
    password: phoenix@123
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1s
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000s

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bruse.mybatis.entity
